### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException exception with JDK 17 

### ISSUE THREAD

**Issue by mbablok** [mefellows/sbt-dotenv#116]
Hello,

There is an exception when starting sbt. Steps to reproduce:

1. Created a new sbt project
```
sbt new scala/scala3.g8
```

2. Add plugins.sbt to project
```
addSbtPlugin("au.com.onegeek" % "sbt-dotenv" % "2.1.204")
```
3. Add dummy .env file to project root
4. Run sbt.

Stacktrace in console:
```
[info] welcome to sbt 1.5.5 (Oracle Corporation Java 17)
[info] loading settings for project test-build from plugins.sbt ...
[info] loading settings for project root from build.sbt ...
[info] set current project to scala3-simple 
[info] .env detected (fileName=.env). About to configure JVM System Environment with new map
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.HashMap java.lang.ProcessEnvironment.theEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @2faa55bb
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$.$anonfun$setEnv$1(DirtyEnvironmentHack.scala:42)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$.setEnv(DirtyEnvironmentHack.scala:38)

```

Seems JDK 17 has changed in respect to `java.lang.ProcessEnvironment`, as a matter of fact I cannot find the class here:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/package-summary.html

**Comment by Philippus** [comment]
duplicate of #101 and #104

**Comment by mbablok** [comment]
Definitely the duplicate, sorry for taking up your time. I was sure I managed the error in JDK 16 with global sbtopts
```
-J--add-opens=java.base/java.util=ALL-UNNAMED
-J--add-opens=java.base/java.lang=ALL-UNNAMED
```
but it turns out that I did it on the other computer.

**Comment by mefellows** [comment]
No worries - it happens :)
