### ISSUE TITLE
Plugin doesn't work on java 17

### ISSUE THREAD

**Issue by jbwheatley** [mefellows/sbt-dotenv#118]
If building a project with java 17, the plugin cannot load the environment. Here is an example sbt output: 
```
[info] welcome to sbt 1.5.5 (Homebrew Java 17)
[info] loading global plugins from ***/.sbt/1.0/plugins
[info] loading project definition from ***/project
[info] loading settings for project *** from plugins.sbt ...
[info] loading project definition from ***/project
[info] loading settings for project userMarvin from build.sbt ...
[info] set current project to *** (in build ***)
[info] .env detected (fileName=meta/environments/dev.env). About to configure JVM System Environment with new map
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.HashMap java.lang.ProcessEnvironment.theEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @6a338cc8
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$.$anonfun$setEnv$1(DirtyEnvironmentHack.scala:42)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$.setEnv(DirtyEnvironmentHack.scala:38)
        at au.com.onegeek.sbtdotenv.SbtDotenv$.applyEnvironment(SbtDotenv.scala:93)
        at au.com.onegeek.sbtdotenv.SbtDotenv$.$anonfun$configureEnvironment$2(SbtDotenv.scala:75)
        at scala.Option.fold(Option.scala:251)
        at au.com.onegeek.sbtdotenv.SbtDotenv$.configureEnvironment(SbtDotenv.scala:75)
        at au.com.onegeek.sbtdotenv.SbtDotenv$autoImport$.$anonfun$dotEnv$1(SbtDotenv.scala:43)
        ...
```

I haven't looked that deeply into it, but I suspect that the dirty environment hack just isn't possible in java 17 as they have made the env inaccessible.

**Comment by Philippus** [comment]
This has been answered before, see #116 for example.

**Comment by jbwheatley** [comment]
is there a way to set those args from the build.sbt? I can do 
`sbt test -J--add-opens=java.base/java.util=ALL-UNNAMED -J--add-opens=java.base/java.lang=ALL-UNNAMED` from the CLI but would be nicer if I could set those options universally in the build

**Comment by Philippus** [comment]
Maybe like this helps?

https://github.com/mefellows/sbt-dotenv/issues/104#issuecomment-846759580

**Comment by jbwheatley** [comment]
ah nice, thanks.
